# Generated by Django 2.1.7 on 2019-05-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('p_price', models.FloatField()),
                ('stocks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('date', models.DateField()),
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('gst', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('date', models.DateField()),
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('gst', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField()),
                ('amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
                ('restock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Restock')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Sale'),
        ),
        migrations.AddField(
            model_name='bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
